# permissions for end users to edit accounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: account-editor-role
rules:
- apiGroups:
  - capabilities.3scale.net
  resources:
  - accounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - accounts/status
  verbs:
  - get
